amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"

map_server:
  ros__parameters:
    use_sim_time: true
    # Para testes sem mapa, desabilite ou use um mapa vazio
    yaml_filename: ""  # vazio, não carrega mapa

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 20.0
    planner_plugin: "GridBased"
    # outros parâmetros do planner aqui

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    controller_plugin: "FollowPath"
    # outros parâmetros do controller

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_time.xml"
    bt_loop_rate: 20

recoveries_server:
  ros__parameters:
    use_sim_time: true

global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: false
    width: 10.0
    height: 10.0
    resolution: 0.05
    static_layer:
      enabled: false  # desabilita mapa estático para evitar erro 'no map received'
    obstacle_layer:
      enabled: true
    inflation_layer:
      enabled: true

local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "odom"
    robot_base_frame: "base_link"
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    obstacle_layer:
      enabled: true
    inflation_layer:
      enabled: true

